model:
  arch: morph_mllm

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  # num_query_token: 32

  # generation configs
  q_former_model: "CKPT_PATH_FOR_MORPH_ENCODER"
  prompt: ""
  taming_config: "./taming_config/taming_model.yaml"
  llama_model_path: "CKPT_PATH_FOR_MLLM"
  taming_ckpt: "CKPT_PATH_FOR_VQGAN"
  llama_tokenizer_path: "PATH_FOR_MULTIMODAL_TOKENIZER"
  lora_r: 64
  lora_alpha: 16


preprocess:
    vq_vis_processor:
        train:
          name: "vqgan_imag"
          image_size: 256
        eval:
          name: "vqgan_imag"
          image_size: 256
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"